import type { Metadata } from "next";
import { ConvexClientProvider } from "../ConvexClientProvider";
import {  Box, Stack } from "@mui/material";
import AppThemeProvider from "../../../theme/theme";
import ThemeModeProvider from "../../../context/Theme&Toast";
import ModeButton from "../../../components/ModeButton/modeButton";
import CustomizedSnackbars from "../../../components/Toast/toast";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({children}: Readonly<{children: React.ReactNode}>) {


  return (
    <html lang="en">

      <body style={{margin:'0'}}>
           <ThemeModeProvider>
                      <AppThemeProvider>

                          <Box sx={{
                    position: 'relative',
                    minHeight: '100vh',
                    overflow: 'hidden',
                    '&::before': {
                      content: '""',
                      position: 'absolute',
                      top: '-200px',
                      left: '50%',
                      transform: 'translateX(-50%)',
                      width: '800px',
                      height: '600px',
                      background: 'radial-gradient(circle, rgba(59,130,246,0.25) 0%, transparent 70%)',
                      pointerEvents: 'none',
                      zIndex: 0,
                    }
                  }}>
                    
                          <Box
                            sx={{
                              justifyContent: "center",
                              width: "100%",
                              minHeight: "100vh",
                              bgcolor:'background.default',
                              backgroundImage: `
                              linear-gradient(rgba(25, 71, 172, 0.22) 1px, transparent 1px), linear-gradient(90deg, rgba(25, 71, 172, 0.22) 1px, transparent 1px)`,
                              backgroundSize: "60px 60px",
                              p:1
                            }}>
                          <ConvexClientProvider>
                            <Stack direction={'row'} spacing={1} sx={{position:'relative'}}>
                            <ModeButton/>

                            </Stack>

                            <Box
                              sx={{
                              display: "flex",
                              flexDirection: "column",
                              alignItems: "center",
                              justifyContent:'center',
                              minHeight:'80vh',
                              }}>
                              {children} 
                            </Box>
                            
                          </ConvexClientProvider>
                          </Box>  
                          <CustomizedSnackbars/>
                  </Box>
                      </AppThemeProvider>
           </ThemeModeProvider>
      </body>
    </html>
  );
}
